// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection-service.proto

package ppconnection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Connection_ConnectionState int32

const (
	Connection_PENDING   Connection_ConnectionState = 0
	Connection_CONNECTED Connection_ConnectionState = 1
)

var Connection_ConnectionState_name = map[int32]string{
	0: "PENDING",
	1: "CONNECTED",
}

var Connection_ConnectionState_value = map[string]int32{
	"PENDING":   0,
	"CONNECTED": 1,
}

func (x Connection_ConnectionState) String() string {
	return proto.EnumName(Connection_ConnectionState_name, int32(x))
}

func (Connection_ConnectionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{1, 0}
}

type Job_JobState int32

const (
	Job_PENDING    Job_JobState = 0
	Job_CONFIGURED Job_JobState = 1
	Job_TESTED     Job_JobState = 2
	Job_FAILED     Job_JobState = 3
)

var Job_JobState_name = map[int32]string{
	0: "PENDING",
	1: "CONFIGURED",
	2: "TESTED",
	3: "FAILED",
}

var Job_JobState_value = map[string]int32{
	"PENDING":    0,
	"CONFIGURED": 1,
	"TESTED":     2,
	"FAILED":     3,
}

func (x Job_JobState) String() string {
	return proto.EnumName(Job_JobState_name, int32(x))
}

func (Job_JobState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{2, 0}
}

type Connections struct {
	Connections          []*Connection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Connections) Reset()         { *m = Connections{} }
func (m *Connections) String() string { return proto.CompactTextString(m) }
func (*Connections) ProtoMessage()    {}
func (*Connections) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{0}
}

func (m *Connections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connections.Unmarshal(m, b)
}
func (m *Connections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connections.Marshal(b, m, deterministic)
}
func (m *Connections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connections.Merge(m, src)
}
func (m *Connections) XXX_Size() int {
	return xxx_messageInfo_Connections.Size(m)
}
func (m *Connections) XXX_DiscardUnknown() {
	xxx_messageInfo_Connections.DiscardUnknown(m)
}

var xxx_messageInfo_Connections proto.InternalMessageInfo

func (m *Connections) GetConnections() []*Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type Connection struct {
	Active               bool                       `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ConnectionState      Connection_ConnectionState `protobuf:"varint,2,opt,name=connectionState,proto3,enum=ppconnection.Connection_ConnectionState" json:"connectionState,omitempty"`
	ConnectionType       int32                      `protobuf:"varint,3,opt,name=connectionType,proto3" json:"connectionType,omitempty"`
	DateCreated          string                     `protobuf:"bytes,4,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	Device               *Device                    `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	IDNumber             string                     `protobuf:"bytes,6,opt,name=IDNumber,proto3" json:"IDNumber,omitempty"`
	NumPhases            int32                      `protobuf:"varint,7,opt,name=numPhases,proto3" json:"numPhases,omitempty"`
	Line1                int32                      `protobuf:"varint,8,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2                int32                      `protobuf:"varint,9,opt,name=line2,proto3" json:"line2,omitempty"`
	Line3                int32                      `protobuf:"varint,10,opt,name=line3,proto3" json:"line3,omitempty"`
	Location             *Location                  `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	ModelType            int32                      `protobuf:"varint,12,opt,name=modelType,proto3" json:"modelType,omitempty"`
	Mount                *Mount                     `protobuf:"bytes,13,opt,name=mount,proto3" json:"mount,omitempty"`
	NickName             string                     `protobuf:"bytes,14,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Type                 string                     `protobuf:"bytes,15,opt,name=type,proto3" json:"type,omitempty"`
	Job                  *Job                       `protobuf:"bytes,16,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{1}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Connection) GetConnectionState() Connection_ConnectionState {
	if m != nil {
		return m.ConnectionState
	}
	return Connection_PENDING
}

func (m *Connection) GetConnectionType() int32 {
	if m != nil {
		return m.ConnectionType
	}
	return 0
}

func (m *Connection) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *Connection) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Connection) GetIDNumber() string {
	if m != nil {
		return m.IDNumber
	}
	return ""
}

func (m *Connection) GetNumPhases() int32 {
	if m != nil {
		return m.NumPhases
	}
	return 0
}

func (m *Connection) GetLine1() int32 {
	if m != nil {
		return m.Line1
	}
	return 0
}

func (m *Connection) GetLine2() int32 {
	if m != nil {
		return m.Line2
	}
	return 0
}

func (m *Connection) GetLine3() int32 {
	if m != nil {
		return m.Line3
	}
	return 0
}

func (m *Connection) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Connection) GetModelType() int32 {
	if m != nil {
		return m.ModelType
	}
	return 0
}

func (m *Connection) GetMount() *Mount {
	if m != nil {
		return m.Mount
	}
	return nil
}

func (m *Connection) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Connection) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Connection) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type Job struct {
	Active               bool         `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Comments             string       `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	Notes                string       `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	DateCreated          string       `protobuf:"bytes,4,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	JobState             Job_JobState `protobuf:"varint,5,opt,name=jobState,proto3,enum=ppconnection.Job_JobState" json:"jobState,omitempty"`
	ReasonForFailure     string       `protobuf:"bytes,6,opt,name=reasonForFailure,proto3" json:"reasonForFailure,omitempty"`
	TestResult           *TestResult  `protobuf:"bytes,7,opt,name=testResult,proto3" json:"testResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Job) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *Job) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Job) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *Job) GetJobState() Job_JobState {
	if m != nil {
		return m.JobState
	}
	return Job_PENDING
}

func (m *Job) GetReasonForFailure() string {
	if m != nil {
		return m.ReasonForFailure
	}
	return ""
}

func (m *Job) GetTestResult() *TestResult {
	if m != nil {
		return m.TestResult
	}
	return nil
}

type TestResult struct {
	DownlinkRSSI         float32  `protobuf:"fixed32,1,opt,name=downlinkRSSI,proto3" json:"downlinkRSSI,omitempty"`
	DownlinkSNR          float32  `protobuf:"fixed32,2,opt,name=downlinkSNR,proto3" json:"downlinkSNR,omitempty"`
	Line1                *Line    `protobuf:"bytes,3,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2                *Line    `protobuf:"bytes,4,opt,name=line2,proto3" json:"line2,omitempty"`
	Line3                *Line    `protobuf:"bytes,5,opt,name=line3,proto3" json:"line3,omitempty"`
	Received             bool     `protobuf:"varint,6,opt,name=received,proto3" json:"received,omitempty"`
	Software             float32  `protobuf:"fixed32,7,opt,name=software,proto3" json:"software,omitempty"`
	UplinkRSSI           float32  `protobuf:"fixed32,8,opt,name=uplinkRSSI,proto3" json:"uplinkRSSI,omitempty"`
	UplinkSNR            float32  `protobuf:"fixed32,9,opt,name=uplinkSNR,proto3" json:"uplinkSNR,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResult) Reset()         { *m = TestResult{} }
func (m *TestResult) String() string { return proto.CompactTextString(m) }
func (*TestResult) ProtoMessage()    {}
func (*TestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{3}
}

func (m *TestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResult.Unmarshal(m, b)
}
func (m *TestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResult.Marshal(b, m, deterministic)
}
func (m *TestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResult.Merge(m, src)
}
func (m *TestResult) XXX_Size() int {
	return xxx_messageInfo_TestResult.Size(m)
}
func (m *TestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResult.DiscardUnknown(m)
}

var xxx_messageInfo_TestResult proto.InternalMessageInfo

func (m *TestResult) GetDownlinkRSSI() float32 {
	if m != nil {
		return m.DownlinkRSSI
	}
	return 0
}

func (m *TestResult) GetDownlinkSNR() float32 {
	if m != nil {
		return m.DownlinkSNR
	}
	return 0
}

func (m *TestResult) GetLine1() *Line {
	if m != nil {
		return m.Line1
	}
	return nil
}

func (m *TestResult) GetLine2() *Line {
	if m != nil {
		return m.Line2
	}
	return nil
}

func (m *TestResult) GetLine3() *Line {
	if m != nil {
		return m.Line3
	}
	return nil
}

func (m *TestResult) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func (m *TestResult) GetSoftware() float32 {
	if m != nil {
		return m.Software
	}
	return 0
}

func (m *TestResult) GetUplinkRSSI() float32 {
	if m != nil {
		return m.UplinkRSSI
	}
	return 0
}

func (m *TestResult) GetUplinkSNR() float32 {
	if m != nil {
		return m.UplinkSNR
	}
	return 0
}

type Line struct {
	Current              float32  `protobuf:"fixed32,1,opt,name=current,proto3" json:"current,omitempty"`
	Voltage              float32  `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Line) Reset()         { *m = Line{} }
func (m *Line) String() string { return proto.CompactTextString(m) }
func (*Line) ProtoMessage()    {}
func (*Line) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{4}
}

func (m *Line) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Line.Unmarshal(m, b)
}
func (m *Line) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Line.Marshal(b, m, deterministic)
}
func (m *Line) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Line.Merge(m, src)
}
func (m *Line) XXX_Size() int {
	return xxx_messageInfo_Line.Size(m)
}
func (m *Line) XXX_DiscardUnknown() {
	xxx_messageInfo_Line.DiscardUnknown(m)
}

var xxx_messageInfo_Line proto.InternalMessageInfo

func (m *Line) GetCurrent() float32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *Line) GetVoltage() float32 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

type Location struct {
	StreetAddress1       string   `protobuf:"bytes,1,opt,name=streetAddress1,proto3" json:"streetAddress1,omitempty"`
	StreetAddress2       string   `protobuf:"bytes,2,opt,name=streetAddress2,proto3" json:"streetAddress2,omitempty"`
	Town                 string   `protobuf:"bytes,3,opt,name=town,proto3" json:"town,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Lng                  float32  `protobuf:"fixed32,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  float32  `protobuf:"fixed32,6,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{5}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetStreetAddress1() string {
	if m != nil {
		return m.StreetAddress1
	}
	return ""
}

func (m *Location) GetStreetAddress2() string {
	if m != nil {
		return m.StreetAddress2
	}
	return ""
}

func (m *Location) GetTown() string {
	if m != nil {
		return m.Town
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Location) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type Mount struct {
	Active               bool      `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	MountNumber          string    `protobuf:"bytes,3,opt,name=mountNumber,proto3" json:"mountNumber,omitempty"`
	MountType            int32     `protobuf:"varint,4,opt,name=mountType,proto3" json:"mountType,omitempty"`
	EnclosureType        int32     `protobuf:"varint,5,opt,name=enclosureType,proto3" json:"enclosureType,omitempty"`
	EnclosureId          string    `protobuf:"bytes,6,opt,name=enclosureId,proto3" json:"enclosureId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{6}
}

func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (m *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(m, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Mount) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Mount) GetMountNumber() string {
	if m != nil {
		return m.MountNumber
	}
	return ""
}

func (m *Mount) GetMountType() int32 {
	if m != nil {
		return m.MountType
	}
	return 0
}

func (m *Mount) GetEnclosureType() int32 {
	if m != nil {
		return m.EnclosureType
	}
	return 0
}

func (m *Mount) GetEnclosureId() string {
	if m != nil {
		return m.EnclosureId
	}
	return ""
}

type Device struct {
	Active               bool         `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	DeviceEUI            string       `protobuf:"bytes,2,opt,name=deviceEUI,proto3" json:"deviceEUI,omitempty"`
	LoRaDetails          *LoRaDetails `protobuf:"bytes,3,opt,name=loRaDetails,proto3" json:"loRaDetails,omitempty"`
	MacAddress           string       `protobuf:"bytes,4,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	ModelType            int32        `protobuf:"varint,5,opt,name=modelType,proto3" json:"modelType,omitempty"`
	MqttConnectionString string       `protobuf:"bytes,6,opt,name=mqttConnectionString,proto3" json:"mqttConnectionString,omitempty"`
	SerialNumber         int32        `protobuf:"varint,7,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	PpNumber             string       `protobuf:"bytes,8,opt,name=ppNumber,proto3" json:"ppNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{7}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Device) GetDeviceEUI() string {
	if m != nil {
		return m.DeviceEUI
	}
	return ""
}

func (m *Device) GetLoRaDetails() *LoRaDetails {
	if m != nil {
		return m.LoRaDetails
	}
	return nil
}

func (m *Device) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *Device) GetModelType() int32 {
	if m != nil {
		return m.ModelType
	}
	return 0
}

func (m *Device) GetMqttConnectionString() string {
	if m != nil {
		return m.MqttConnectionString
	}
	return ""
}

func (m *Device) GetSerialNumber() int32 {
	if m != nil {
		return m.SerialNumber
	}
	return 0
}

func (m *Device) GetPpNumber() string {
	if m != nil {
		return m.PpNumber
	}
	return ""
}

type LoRaDetails struct {
	ApplicationEUI         string   `protobuf:"bytes,1,opt,name=applicationEUI,proto3" json:"applicationEUI,omitempty"`
	ApplicationSoftwareKey string   `protobuf:"bytes,2,opt,name=applicationSoftwareKey,proto3" json:"applicationSoftwareKey,omitempty"`
	DeviceAddress          string   `protobuf:"bytes,3,opt,name=deviceAddress,proto3" json:"deviceAddress,omitempty"`
	NetworkSoftwareKey     string   `protobuf:"bytes,4,opt,name=networkSoftwareKey,proto3" json:"networkSoftwareKey,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *LoRaDetails) Reset()         { *m = LoRaDetails{} }
func (m *LoRaDetails) String() string { return proto.CompactTextString(m) }
func (*LoRaDetails) ProtoMessage()    {}
func (*LoRaDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{8}
}

func (m *LoRaDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoRaDetails.Unmarshal(m, b)
}
func (m *LoRaDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoRaDetails.Marshal(b, m, deterministic)
}
func (m *LoRaDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoRaDetails.Merge(m, src)
}
func (m *LoRaDetails) XXX_Size() int {
	return xxx_messageInfo_LoRaDetails.Size(m)
}
func (m *LoRaDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_LoRaDetails.DiscardUnknown(m)
}

var xxx_messageInfo_LoRaDetails proto.InternalMessageInfo

func (m *LoRaDetails) GetApplicationEUI() string {
	if m != nil {
		return m.ApplicationEUI
	}
	return ""
}

func (m *LoRaDetails) GetApplicationSoftwareKey() string {
	if m != nil {
		return m.ApplicationSoftwareKey
	}
	return ""
}

func (m *LoRaDetails) GetDeviceAddress() string {
	if m != nil {
		return m.DeviceAddress
	}
	return ""
}

func (m *LoRaDetails) GetNetworkSoftwareKey() string {
	if m != nil {
		return m.NetworkSoftwareKey
	}
	return ""
}

type GetConnectionsRequest struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectionsRequest) Reset()         { *m = GetConnectionsRequest{} }
func (m *GetConnectionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetConnectionsRequest) ProtoMessage()    {}
func (*GetConnectionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{9}
}

func (m *GetConnectionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectionsRequest.Unmarshal(m, b)
}
func (m *GetConnectionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectionsRequest.Marshal(b, m, deterministic)
}
func (m *GetConnectionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectionsRequest.Merge(m, src)
}
func (m *GetConnectionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetConnectionsRequest.Size(m)
}
func (m *GetConnectionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectionsRequest proto.InternalMessageInfo

func (m *GetConnectionsRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Identifier struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{10}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type UpdateConnectionRequest struct {
	Identifier           string      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Connection           *Connection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateConnectionRequest) Reset()         { *m = UpdateConnectionRequest{} }
func (m *UpdateConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConnectionRequest) ProtoMessage()    {}
func (*UpdateConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{11}
}

func (m *UpdateConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConnectionRequest.Unmarshal(m, b)
}
func (m *UpdateConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConnectionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConnectionRequest.Merge(m, src)
}
func (m *UpdateConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConnectionRequest.Size(m)
}
func (m *UpdateConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConnectionRequest proto.InternalMessageInfo

func (m *UpdateConnectionRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateConnectionRequest) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

type UpdateMountRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Mount                *Mount   `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMountRequest) Reset()         { *m = UpdateMountRequest{} }
func (m *UpdateMountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMountRequest) ProtoMessage()    {}
func (*UpdateMountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{12}
}

func (m *UpdateMountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMountRequest.Unmarshal(m, b)
}
func (m *UpdateMountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMountRequest.Merge(m, src)
}
func (m *UpdateMountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMountRequest.Size(m)
}
func (m *UpdateMountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMountRequest proto.InternalMessageInfo

func (m *UpdateMountRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateMountRequest) GetMount() *Mount {
	if m != nil {
		return m.Mount
	}
	return nil
}

type UpdateDeviceRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Device               *Device  `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceRequest) Reset()         { *m = UpdateDeviceRequest{} }
func (m *UpdateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRequest) ProtoMessage()    {}
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{13}
}

func (m *UpdateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRequest.Unmarshal(m, b)
}
func (m *UpdateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRequest.Merge(m, src)
}
func (m *UpdateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRequest.Size(m)
}
func (m *UpdateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRequest proto.InternalMessageInfo

func (m *UpdateDeviceRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type UpdateConnectionStateRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	ConnectionState      string   `protobuf:"bytes,2,opt,name=connectionState,proto3" json:"connectionState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConnectionStateRequest) Reset()         { *m = UpdateConnectionStateRequest{} }
func (m *UpdateConnectionStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConnectionStateRequest) ProtoMessage()    {}
func (*UpdateConnectionStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{14}
}

func (m *UpdateConnectionStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConnectionStateRequest.Unmarshal(m, b)
}
func (m *UpdateConnectionStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConnectionStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConnectionStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConnectionStateRequest.Merge(m, src)
}
func (m *UpdateConnectionStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConnectionStateRequest.Size(m)
}
func (m *UpdateConnectionStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConnectionStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConnectionStateRequest proto.InternalMessageInfo

func (m *UpdateConnectionStateRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateConnectionStateRequest) GetConnectionState() string {
	if m != nil {
		return m.ConnectionState
	}
	return ""
}

type UpdateJobRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Job                  *Job     `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobRequest) Reset()         { *m = UpdateJobRequest{} }
func (m *UpdateJobRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJobRequest) ProtoMessage()    {}
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{15}
}

func (m *UpdateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobRequest.Unmarshal(m, b)
}
func (m *UpdateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobRequest.Marshal(b, m, deterministic)
}
func (m *UpdateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobRequest.Merge(m, src)
}
func (m *UpdateJobRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJobRequest.Size(m)
}
func (m *UpdateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobRequest proto.InternalMessageInfo

func (m *UpdateJobRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateLinesRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Line1                int32    `protobuf:"varint,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2                int32    `protobuf:"varint,3,opt,name=line2,proto3" json:"line2,omitempty"`
	Line3                int32    `protobuf:"varint,4,opt,name=line3,proto3" json:"line3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLinesRequest) Reset()         { *m = UpdateLinesRequest{} }
func (m *UpdateLinesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLinesRequest) ProtoMessage()    {}
func (*UpdateLinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{16}
}

func (m *UpdateLinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLinesRequest.Unmarshal(m, b)
}
func (m *UpdateLinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLinesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLinesRequest.Merge(m, src)
}
func (m *UpdateLinesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLinesRequest.Size(m)
}
func (m *UpdateLinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLinesRequest proto.InternalMessageInfo

func (m *UpdateLinesRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *UpdateLinesRequest) GetLine1() int32 {
	if m != nil {
		return m.Line1
	}
	return 0
}

func (m *UpdateLinesRequest) GetLine2() int32 {
	if m != nil {
		return m.Line2
	}
	return 0
}

func (m *UpdateLinesRequest) GetLine3() int32 {
	if m != nil {
		return m.Line3
	}
	return 0
}

type GetAddressRequest struct {
	InstallNumber        string   `protobuf:"bytes,1,opt,name=installNumber,proto3" json:"installNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressRequest) Reset()         { *m = GetAddressRequest{} }
func (m *GetAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddressRequest) ProtoMessage()    {}
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{17}
}

func (m *GetAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressRequest.Unmarshal(m, b)
}
func (m *GetAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressRequest.Merge(m, src)
}
func (m *GetAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddressRequest.Size(m)
}
func (m *GetAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressRequest proto.InternalMessageInfo

func (m *GetAddressRequest) GetInstallNumber() string {
	if m != nil {
		return m.InstallNumber
	}
	return ""
}

type GetDeviceBySerialNumberRequest struct {
	SerialNumber         string   `protobuf:"bytes,1,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceBySerialNumberRequest) Reset()         { *m = GetDeviceBySerialNumberRequest{} }
func (m *GetDeviceBySerialNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceBySerialNumberRequest) ProtoMessage()    {}
func (*GetDeviceBySerialNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{18}
}

func (m *GetDeviceBySerialNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceBySerialNumberRequest.Unmarshal(m, b)
}
func (m *GetDeviceBySerialNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceBySerialNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceBySerialNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceBySerialNumberRequest.Merge(m, src)
}
func (m *GetDeviceBySerialNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceBySerialNumberRequest.Size(m)
}
func (m *GetDeviceBySerialNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceBySerialNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceBySerialNumberRequest proto.InternalMessageInfo

func (m *GetDeviceBySerialNumberRequest) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

type Response struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{19}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f86ad761877d5c, []int{20}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("ppconnection.Connection_ConnectionState", Connection_ConnectionState_name, Connection_ConnectionState_value)
	proto.RegisterEnum("ppconnection.Job_JobState", Job_JobState_name, Job_JobState_value)
	proto.RegisterType((*Connections)(nil), "ppconnection.Connections")
	proto.RegisterType((*Connection)(nil), "ppconnection.Connection")
	proto.RegisterType((*Job)(nil), "ppconnection.Job")
	proto.RegisterType((*TestResult)(nil), "ppconnection.TestResult")
	proto.RegisterType((*Line)(nil), "ppconnection.Line")
	proto.RegisterType((*Location)(nil), "ppconnection.Location")
	proto.RegisterType((*Mount)(nil), "ppconnection.Mount")
	proto.RegisterType((*Device)(nil), "ppconnection.Device")
	proto.RegisterType((*LoRaDetails)(nil), "ppconnection.LoRaDetails")
	proto.RegisterType((*GetConnectionsRequest)(nil), "ppconnection.GetConnectionsRequest")
	proto.RegisterType((*Identifier)(nil), "ppconnection.Identifier")
	proto.RegisterType((*UpdateConnectionRequest)(nil), "ppconnection.UpdateConnectionRequest")
	proto.RegisterType((*UpdateMountRequest)(nil), "ppconnection.UpdateMountRequest")
	proto.RegisterType((*UpdateDeviceRequest)(nil), "ppconnection.UpdateDeviceRequest")
	proto.RegisterType((*UpdateConnectionStateRequest)(nil), "ppconnection.UpdateConnectionStateRequest")
	proto.RegisterType((*UpdateJobRequest)(nil), "ppconnection.UpdateJobRequest")
	proto.RegisterType((*UpdateLinesRequest)(nil), "ppconnection.UpdateLinesRequest")
	proto.RegisterType((*GetAddressRequest)(nil), "ppconnection.GetAddressRequest")
	proto.RegisterType((*GetDeviceBySerialNumberRequest)(nil), "ppconnection.GetDeviceBySerialNumberRequest")
	proto.RegisterType((*Response)(nil), "ppconnection.Response")
	proto.RegisterType((*Empty)(nil), "ppconnection.Empty")
}

func init() { proto.RegisterFile("connection-service.proto", fileDescriptor_80f86ad761877d5c) }

var fileDescriptor_80f86ad761877d5c = []byte{
	// 1410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0x28, 0xcb, 0xa6, 0x46, 0xb6, 0xa3, 0x6c, 0xfe, 0x18, 0x21, 0x48, 0xd5, 0x4d, 0x5a,
	0xa8, 0x41, 0xe2, 0x22, 0x32, 0x10, 0xb4, 0xe9, 0xa1, 0x48, 0x2c, 0x59, 0x55, 0x92, 0x2a, 0xc1,
	0xca, 0x41, 0x4f, 0x45, 0x40, 0x4b, 0x1b, 0x87, 0x31, 0xb5, 0x64, 0xc8, 0x95, 0x0d, 0xbf, 0x53,
	0xfb, 0x14, 0x05, 0x7a, 0xee, 0xbd, 0x97, 0xbe, 0x40, 0xdf, 0xa1, 0xd8, 0x1f, 0x92, 0x4b, 0x4a,
	0x54, 0x04, 0xf4, 0x10, 0x80, 0xf3, 0xcd, 0x68, 0x76, 0x66, 0x76, 0xe6, 0xdb, 0x71, 0xc0, 0x99,
	0x04, 0x8c, 0xd1, 0x09, 0xf7, 0x02, 0xf6, 0x28, 0xa6, 0xd1, 0xb9, 0x37, 0xa1, 0xfb, 0x61, 0x14,
	0xf0, 0x00, 0xed, 0x84, 0x61, 0xa6, 0xc3, 0x43, 0x68, 0x1c, 0xa6, 0x52, 0x8c, 0x9e, 0x42, 0x23,
	0x53, 0xc6, 0x4e, 0xa5, 0x5d, 0xed, 0x34, 0xba, 0xce, 0xbe, 0xf9, 0x93, 0xfd, 0xcc, 0x9e, 0x98,
	0xc6, 0xf8, 0xdf, 0x4d, 0x80, 0x4c, 0x87, 0x6e, 0xc2, 0x96, 0x3b, 0xe1, 0xde, 0x39, 0x75, 0x2a,
	0xed, 0x4a, 0xc7, 0x26, 0x5a, 0x42, 0x04, 0xae, 0x64, 0xbf, 0x1a, 0x73, 0x97, 0x53, 0xc7, 0x6a,
	0x57, 0x3a, 0x7b, 0xdd, 0x4e, 0xd9, 0x31, 0xc6, 0xa7, 0xb4, 0x27, 0x45, 0x07, 0xe8, 0x6b, 0xd8,
	0xcb, 0xa0, 0xe3, 0xcb, 0x90, 0x3a, 0xd5, 0x76, 0xa5, 0x53, 0x23, 0x05, 0x14, 0xb5, 0xa1, 0x31,
	0x75, 0x39, 0x3d, 0x8c, 0xa8, 0xcb, 0xe9, 0xd4, 0xd9, 0x6c, 0x57, 0x3a, 0x75, 0x62, 0x42, 0xe8,
	0x21, 0x6c, 0x4d, 0xa9, 0xa8, 0x96, 0x53, 0x6b, 0x57, 0x3a, 0x8d, 0xee, 0xf5, 0x7c, 0x50, 0x3d,
	0xa9, 0x23, 0xda, 0x06, 0xb5, 0xc0, 0x1e, 0xf6, 0x46, 0xf3, 0xd9, 0x09, 0x8d, 0x9c, 0x2d, 0xe9,
	0x2c, 0x95, 0xd1, 0x1d, 0xa8, 0xb3, 0xf9, 0xec, 0xcd, 0x07, 0x37, 0xa6, 0xb1, 0xb3, 0x2d, 0xc3,
	0xc9, 0x00, 0x74, 0x1d, 0x6a, 0xbe, 0xc7, 0xe8, 0x63, 0xc7, 0x96, 0x1a, 0x25, 0x24, 0x68, 0xd7,
	0xa9, 0x67, 0x68, 0x37, 0x41, 0x0f, 0x1c, 0xc8, 0xd0, 0x03, 0xd4, 0x05, 0xdb, 0x0f, 0x26, 0xae,
	0x08, 0xcb, 0x69, 0xc8, 0x58, 0x6f, 0xe6, 0x63, 0x7d, 0xa5, 0xb5, 0x24, 0xb5, 0x13, 0x31, 0xcd,
	0x82, 0x29, 0xf5, 0x65, 0x89, 0x76, 0x54, 0x4c, 0x29, 0x80, 0xbe, 0x81, 0xda, 0x2c, 0x98, 0x33,
	0xee, 0xec, 0x4a, 0x77, 0xd7, 0xf2, 0xee, 0x7e, 0x16, 0x2a, 0xa2, 0x2c, 0x44, 0xe2, 0xcc, 0x9b,
	0x9c, 0x8d, 0xdc, 0x19, 0x75, 0xf6, 0x54, 0xe2, 0x89, 0x8c, 0x10, 0x6c, 0x72, 0xe1, 0xff, 0x8a,
	0xc4, 0xe5, 0x37, 0xba, 0x07, 0xd5, 0x8f, 0xc1, 0x89, 0xd3, 0x94, 0x8e, 0xaf, 0xe6, 0x1d, 0xbf,
	0x08, 0x4e, 0x88, 0xd0, 0xe2, 0x47, 0x70, 0xa5, 0x70, 0xd3, 0xa8, 0x01, 0xdb, 0x6f, 0xfa, 0xa3,
	0xde, 0x70, 0x34, 0x68, 0x6e, 0xa0, 0x5d, 0xa8, 0x1f, 0xbe, 0x1e, 0x8d, 0xfa, 0x87, 0xc7, 0xfd,
	0x5e, 0xb3, 0x82, 0xff, 0xb2, 0xa0, 0xfa, 0x22, 0x38, 0x29, 0x6d, 0xb4, 0x16, 0xd8, 0x93, 0x60,
	0x36, 0xa3, 0x8c, 0xc7, 0xb2, 0xc3, 0xea, 0x24, 0x95, 0x45, 0x49, 0x59, 0xc0, 0x69, 0x2c, 0xfb,
	0xa4, 0x4e, 0x94, 0xb0, 0x46, 0x7b, 0x3c, 0x01, 0xfb, 0x63, 0x70, 0xa2, 0xba, 0xb6, 0x26, 0xbb,
	0xb6, 0xb5, 0x90, 0x8c, 0xf8, 0xa7, 0xfa, 0x34, 0xb5, 0x45, 0x0f, 0xa0, 0x19, 0x51, 0x37, 0x0e,
	0xd8, 0x51, 0x10, 0x1d, 0xb9, 0x9e, 0x3f, 0x8f, 0xa8, 0x6e, 0x98, 0x05, 0x1c, 0x7d, 0x07, 0xc0,
	0x69, 0xcc, 0x09, 0x8d, 0xe7, 0x3e, 0x97, 0x9d, 0xb3, 0x30, 0x82, 0xc7, 0xa9, 0x9e, 0x18, 0xb6,
	0xf8, 0x47, 0xb0, 0x93, 0xb3, 0xf3, 0x95, 0xdb, 0x03, 0x38, 0x7c, 0x3d, 0x3a, 0x1a, 0x0e, 0xde,
	0x12, 0x51, 0x3a, 0x04, 0xb0, 0x75, 0xdc, 0x1f, 0x8b, 0x32, 0x5a, 0xe2, 0xfb, 0xe8, 0xd9, 0xf0,
	0x55, 0xbf, 0xd7, 0xac, 0xe2, 0x3f, 0x2d, 0x80, 0xcc, 0x37, 0xc2, 0xb0, 0x33, 0x0d, 0x2e, 0x98,
	0xef, 0xb1, 0x33, 0x32, 0x1e, 0x0f, 0x65, 0x7d, 0x2d, 0x92, 0xc3, 0x64, 0xcd, 0xb4, 0x3c, 0x1e,
	0x11, 0x59, 0x68, 0x8b, 0x98, 0x10, 0xea, 0x24, 0xad, 0x5e, 0x95, 0xa9, 0xa0, 0x42, 0x97, 0x7a,
	0x8c, 0x26, 0xed, 0xdf, 0x49, 0xda, 0x7f, 0x73, 0xb5, 0x65, 0x37, 0xb1, 0x3c, 0xd0, 0x53, 0x5a,
	0x6a, 0x79, 0x20, 0xba, 0x20, 0xa2, 0x13, 0xea, 0x9d, 0xd3, 0xa9, 0xac, 0xb8, 0x4d, 0x52, 0x59,
	0xe8, 0xe2, 0xe0, 0x3d, 0xbf, 0x70, 0x23, 0x2a, 0xeb, 0x6c, 0x91, 0x54, 0x46, 0x77, 0x01, 0xe6,
	0x61, 0x9a, 0xb9, 0x2d, 0xb5, 0x06, 0x22, 0x46, 0x49, 0x49, 0x22, 0xeb, 0xba, 0x54, 0x67, 0x00,
	0x7e, 0x0a, 0x9b, 0x22, 0x08, 0xe4, 0xc0, 0xf6, 0x64, 0x1e, 0x45, 0x94, 0x71, 0x5d, 0xbc, 0x44,
	0x14, 0x9a, 0xf3, 0xc0, 0xe7, 0xee, 0x29, 0xd5, 0x35, 0x4b, 0x44, 0xfc, 0x5b, 0x05, 0xec, 0x64,
	0x76, 0x05, 0xb3, 0xc5, 0x3c, 0xa2, 0x94, 0x3f, 0x9b, 0x4e, 0x23, 0x1a, 0xc7, 0x8f, 0xa5, 0x9f,
	0x3a, 0x29, 0xa0, 0x0b, 0x76, 0x5d, 0xdd, 0xf2, 0x05, 0x54, 0x0e, 0x67, 0x70, 0xc1, 0x74, 0xdf,
	0xcb, 0x6f, 0x19, 0xa4, 0x98, 0xea, 0xe8, 0x52, 0xb7, 0x7c, 0x22, 0xa2, 0x26, 0x54, 0x7d, 0x76,
	0x2a, 0x8b, 0x6c, 0x11, 0xf1, 0x29, 0x11, 0x97, 0xcb, 0x4a, 0x0a, 0xc4, 0xe5, 0xf8, 0xef, 0x0a,
	0xd4, 0x24, 0x37, 0x94, 0x0e, 0xa2, 0xc9, 0x54, 0xd6, 0x9a, 0x4c, 0xd5, 0x86, 0x86, 0x64, 0x1a,
	0x4d, 0xae, 0x2a, 0x5c, 0x13, 0x52, 0x5c, 0x36, 0x67, 0x5c, 0x72, 0xd9, 0x66, 0xc2, 0x65, 0x1a,
	0x40, 0xf7, 0x61, 0x97, 0xb2, 0x89, 0x1f, 0xc4, 0xf3, 0x88, 0x4a, 0x8b, 0x9a, 0xb4, 0xc8, 0x83,
	0xe2, 0x94, 0x14, 0x18, 0x4e, 0xf5, 0x44, 0x9a, 0x10, 0xfe, 0xdd, 0x82, 0x2d, 0x45, 0xfa, 0xa5,
	0xe9, 0xdd, 0x81, 0xba, 0x7a, 0x0e, 0xfa, 0x6f, 0x87, 0xba, 0xea, 0x19, 0x80, 0x7e, 0x80, 0x86,
	0x1f, 0x10, 0xb7, 0x47, 0xb9, 0xeb, 0xf9, 0xb1, 0x9e, 0x81, 0xdb, 0xc5, 0xfc, 0x53, 0x03, 0x62,
	0x5a, 0x8b, 0x26, 0x9c, 0xb9, 0x13, 0x7d, 0x79, 0xfa, 0x72, 0x0c, 0x24, 0xcf, 0xe7, 0xb5, 0x22,
	0x9f, 0x77, 0xe1, 0xfa, 0xec, 0x13, 0xe7, 0x26, 0xa7, 0x46, 0x1e, 0x3b, 0xd5, 0x69, 0x2e, 0xd5,
	0x89, 0x91, 0x8f, 0x69, 0xe4, 0xb9, 0xbe, 0x2e, 0xbc, 0x7a, 0xb8, 0x72, 0x98, 0x18, 0x9b, 0x30,
	0xd4, 0x7a, 0x5b, 0x11, 0x6b, 0x22, 0xe3, 0x3f, 0x2a, 0xd0, 0x30, 0xd2, 0x11, 0x7d, 0xe9, 0x86,
	0xa1, 0xef, 0xa9, 0x6b, 0x15, 0x15, 0xd2, 0xfd, 0x9b, 0x47, 0xd1, 0x13, 0xb8, 0x69, 0x20, 0x63,
	0x3d, 0x85, 0x2f, 0xe9, 0xa5, 0xae, 0x68, 0x89, 0x56, 0xdc, 0xb3, 0xaa, 0x75, 0x52, 0x24, 0xd5,
	0x29, 0x79, 0x10, 0xed, 0x03, 0x62, 0x94, 0x5f, 0x04, 0xd1, 0x99, 0xe9, 0x59, 0xd5, 0x73, 0x89,
	0x06, 0x7f, 0x0b, 0x37, 0x06, 0xd4, 0x28, 0x4e, 0x4c, 0xe8, 0xa7, 0x39, 0x8d, 0x4b, 0x5b, 0x1c,
	0x3f, 0x04, 0x18, 0x4e, 0x29, 0xe3, 0xde, 0x7b, 0x8f, 0x46, 0xe2, 0xda, 0xbc, 0x54, 0xd2, 0x09,
	0x1b, 0x08, 0x8e, 0xe1, 0xd6, 0xdb, 0x50, 0x3e, 0x2b, 0xd9, 0x2a, 0xa5, 0x0f, 0xf8, 0xcc, 0x4f,
	0xc5, 0xe3, 0x90, 0x35, 0x8e, 0x9e, 0xa6, 0xf2, 0xfd, 0xcc, 0xb0, 0xc5, 0xef, 0x00, 0xa9, 0x43,
	0xd5, 0x43, 0xbe, 0xe6, 0x79, 0xe9, 0x4e, 0x60, 0x7d, 0x6e, 0x27, 0xc0, 0x13, 0xb8, 0xa6, 0x0e,
	0xd0, 0x4b, 0xd2, 0x9a, 0x27, 0x64, 0x1b, 0x97, 0xf5, 0xf9, 0x8d, 0x0b, 0x7f, 0x80, 0x3b, 0xc5,
	0xd2, 0xa9, 0xb7, 0x76, 0xcd, 0xd3, 0x3a, 0xcb, 0xb7, 0xcf, 0xfa, 0xc2, 0x4e, 0x89, 0x7f, 0x81,
	0xa6, 0x3a, 0x49, 0xec, 0x27, 0x6b, 0x7a, 0xd7, 0x6b, 0x8e, 0xb5, 0x72, 0xcd, 0x39, 0x4f, 0x2e,
	0x42, 0xbc, 0x10, 0xf1, 0xba, 0xae, 0xd3, 0x85, 0xd1, 0x5a, 0xba, 0x30, 0x56, 0x97, 0x2e, 0x8c,
	0x9b, 0xc6, 0xc2, 0x88, 0xbf, 0x87, 0xab, 0x83, 0xf4, 0x25, 0x48, 0x8e, 0xbd, 0x0f, 0xbb, 0x1e,
	0x8b, 0xb9, 0xeb, 0x27, 0x03, 0xaf, 0x4e, 0xce, 0x83, 0xb8, 0x07, 0x77, 0x07, 0x94, 0xab, 0xab,
	0x78, 0x7e, 0x39, 0x36, 0xc8, 0x20, 0xf1, 0x53, 0xe4, 0x0d, 0xe5, 0x26, 0x87, 0xe1, 0x36, 0xd8,
	0x84, 0xc6, 0x61, 0xc0, 0x62, 0x2a, 0x42, 0x8c, 0x68, 0xe8, 0x5f, 0x6a, 0x43, 0x25, 0xe0, 0x6d,
	0xa8, 0xf5, 0x67, 0x21, 0xbf, 0xec, 0xfe, 0x63, 0xc3, 0x55, 0xe3, 0x86, 0xd5, 0x1f, 0x30, 0x88,
	0xc0, 0x5e, 0x7e, 0x2c, 0xd1, 0xbd, 0x7c, 0x8d, 0x97, 0x0e, 0x6d, 0xeb, 0x76, 0xd9, 0x7c, 0xc4,
	0x78, 0x03, 0xf5, 0x01, 0x0d, 0x28, 0x7f, 0xee, 0xbb, 0xec, 0xcc, 0xf8, 0xe3, 0xa5, 0xd0, 0xe7,
	0x32, 0xa8, 0x56, 0xe9, 0x9c, 0x49, 0x37, 0xbb, 0xb9, 0xc3, 0x51, 0xc1, 0x38, 0x63, 0x87, 0x95,
	0x6e, 0x86, 0xd0, 0x30, 0x86, 0x14, 0xb5, 0xf3, 0xa6, 0x8b, 0xf3, 0xdb, 0x2a, 0xbc, 0xa4, 0x49,
	0x7d, 0xf1, 0x06, 0xfa, 0x09, 0x9a, 0x6a, 0x6b, 0x2d, 0x0f, 0x2a, 0xd3, 0xb4, 0x4a, 0xc3, 0xc5,
	0x1b, 0xe8, 0x35, 0xdc, 0x52, 0x9e, 0xde, 0x50, 0x36, 0xf5, 0xd8, 0xe9, 0xff, 0x76, 0x38, 0x4e,
	0x46, 0xcb, 0xf0, 0xf4, 0xd5, 0xb2, 0x54, 0x17, 0xf8, 0x71, 0x45, 0xbe, 0x47, 0xd0, 0xec, 0x51,
	0x9f, 0xae, 0xca, 0xd7, 0xb8, 0x84, 0x72, 0x3f, 0x2f, 0x61, 0xc7, 0xa4, 0x31, 0xf4, 0xe5, 0xb2,
	0xc0, 0x72, 0x14, 0xb7, 0xc2, 0xd9, 0xaf, 0x70, 0x63, 0x29, 0x5d, 0xa1, 0x07, 0xab, 0xd3, 0x35,
	0x39, 0x6d, 0x85, 0xfb, 0x3e, 0xd4, 0x53, 0x8e, 0x42, 0x77, 0x97, 0xb9, 0xcc, 0xc8, 0x6b, 0x85,
	0x9b, 0xb4, 0xeb, 0x24, 0x23, 0x2d, 0xef, 0x3a, 0x93, 0xac, 0x56, 0xb8, 0x1a, 0x00, 0x64, 0x24,
	0x83, 0xbe, 0x58, 0x18, 0xcf, 0x3c, 0xfd, 0xb4, 0x4a, 0x16, 0x41, 0xbc, 0x81, 0xde, 0xc1, 0xad,
	0x12, 0xca, 0x41, 0x0f, 0x17, 0xbc, 0xae, 0x60, 0xa6, 0xd6, 0xd2, 0xf7, 0x04, 0x6f, 0x9c, 0x6c,
	0xc9, 0xff, 0x0e, 0x39, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x29, 0xd8, 0xf4, 0xa9, 0x2a, 0x11,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*Connections, error)
	GetBlankConnection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Connection, error)
	GetConnection(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Connection, error)
	UpdateMount(ctx context.Context, in *UpdateMountRequest, opts ...grpc.CallOption) (*Response, error)
	CreateConnection(ctx context.Context, in *Connection, opts ...grpc.CallOption) (*Identifier, error)
	CreatePendingConnection(ctx context.Context, in *Connection, opts ...grpc.CallOption) (*Identifier, error)
	UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteConnection(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Response, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateConnectionState(ctx context.Context, in *UpdateConnectionStateRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateLines(ctx context.Context, in *UpdateLinesRequest, opts ...grpc.CallOption) (*Response, error)
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Location, error)
	GetDeviceBySerialNumber(ctx context.Context, in *GetDeviceBySerialNumberRequest, opts ...grpc.CallOption) (*Device, error)
}

type connectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectionServiceClient(cc *grpc.ClientConn) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) GetConnections(ctx context.Context, in *GetConnectionsRequest, opts ...grpc.CallOption) (*Connections, error) {
	out := new(Connections)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/GetConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetBlankConnection(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Connection, error) {
	out := new(Connection)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/GetBlankConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetConnection(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Connection, error) {
	out := new(Connection)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/GetConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateMount(ctx context.Context, in *UpdateMountRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateMount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) CreateConnection(ctx context.Context, in *Connection, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/CreateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) CreatePendingConnection(ctx context.Context, in *Connection, opts ...grpc.CallOption) (*Identifier, error) {
	out := new(Identifier)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/CreatePendingConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) DeleteConnection(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/DeleteConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateConnectionState(ctx context.Context, in *UpdateConnectionStateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateConnectionState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) UpdateLines(ctx context.Context, in *UpdateLinesRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/UpdateLines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/GetAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetDeviceBySerialNumber(ctx context.Context, in *GetDeviceBySerialNumberRequest, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/ppconnection.ConnectionService/GetDeviceBySerialNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
type ConnectionServiceServer interface {
	GetConnections(context.Context, *GetConnectionsRequest) (*Connections, error)
	GetBlankConnection(context.Context, *Empty) (*Connection, error)
	GetConnection(context.Context, *Identifier) (*Connection, error)
	UpdateMount(context.Context, *UpdateMountRequest) (*Response, error)
	CreateConnection(context.Context, *Connection) (*Identifier, error)
	CreatePendingConnection(context.Context, *Connection) (*Identifier, error)
	UpdateConnection(context.Context, *UpdateConnectionRequest) (*Response, error)
	DeleteConnection(context.Context, *Identifier) (*Response, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*Response, error)
	UpdateConnectionState(context.Context, *UpdateConnectionStateRequest) (*Response, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*Response, error)
	UpdateLines(context.Context, *UpdateLinesRequest) (*Response, error)
	GetAddress(context.Context, *GetAddressRequest) (*Location, error)
	GetDeviceBySerialNumber(context.Context, *GetDeviceBySerialNumberRequest) (*Device, error)
}

// UnimplementedConnectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConnectionServiceServer struct {
}

func (*UnimplementedConnectionServiceServer) GetConnections(ctx context.Context, req *GetConnectionsRequest) (*Connections, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnections not implemented")
}
func (*UnimplementedConnectionServiceServer) GetBlankConnection(ctx context.Context, req *Empty) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlankConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) GetConnection(ctx context.Context, req *Identifier) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateMount(ctx context.Context, req *UpdateMountRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMount not implemented")
}
func (*UnimplementedConnectionServiceServer) CreateConnection(ctx context.Context, req *Connection) (*Identifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) CreatePendingConnection(ctx context.Context, req *Connection) (*Identifier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePendingConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateConnection(ctx context.Context, req *UpdateConnectionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) DeleteConnection(ctx context.Context, req *Identifier) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConnection not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateDevice(ctx context.Context, req *UpdateDeviceRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateConnectionState(ctx context.Context, req *UpdateConnectionStateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConnectionState not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateJob(ctx context.Context, req *UpdateJobRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (*UnimplementedConnectionServiceServer) UpdateLines(ctx context.Context, req *UpdateLinesRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLines not implemented")
}
func (*UnimplementedConnectionServiceServer) GetAddress(ctx context.Context, req *GetAddressRequest) (*Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (*UnimplementedConnectionServiceServer) GetDeviceBySerialNumber(ctx context.Context, req *GetDeviceBySerialNumberRequest) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceBySerialNumber not implemented")
}

func RegisterConnectionServiceServer(s *grpc.Server, srv ConnectionServiceServer) {
	s.RegisterService(&_ConnectionService_serviceDesc, srv)
}

func _ConnectionService_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/GetConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetConnections(ctx, req.(*GetConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetBlankConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetBlankConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/GetBlankConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetBlankConnection(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/GetConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetConnection(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateMount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateMount(ctx, req.(*UpdateMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/CreateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).CreateConnection(ctx, req.(*Connection))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_CreatePendingConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).CreatePendingConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/CreatePendingConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).CreatePendingConnection(ctx, req.(*Connection))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateConnection(ctx, req.(*UpdateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/DeleteConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).DeleteConnection(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateConnectionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateConnectionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateConnectionState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateConnectionState(ctx, req.(*UpdateConnectionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_UpdateLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).UpdateLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/UpdateLines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).UpdateLines(ctx, req.(*UpdateLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetAddress(ctx, req.(*GetAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetDeviceBySerialNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceBySerialNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetDeviceBySerialNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppconnection.ConnectionService/GetDeviceBySerialNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetDeviceBySerialNumber(ctx, req.(*GetDeviceBySerialNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ppconnection.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnections",
			Handler:    _ConnectionService_GetConnections_Handler,
		},
		{
			MethodName: "GetBlankConnection",
			Handler:    _ConnectionService_GetBlankConnection_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _ConnectionService_GetConnection_Handler,
		},
		{
			MethodName: "UpdateMount",
			Handler:    _ConnectionService_UpdateMount_Handler,
		},
		{
			MethodName: "CreateConnection",
			Handler:    _ConnectionService_CreateConnection_Handler,
		},
		{
			MethodName: "CreatePendingConnection",
			Handler:    _ConnectionService_CreatePendingConnection_Handler,
		},
		{
			MethodName: "UpdateConnection",
			Handler:    _ConnectionService_UpdateConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _ConnectionService_DeleteConnection_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _ConnectionService_UpdateDevice_Handler,
		},
		{
			MethodName: "UpdateConnectionState",
			Handler:    _ConnectionService_UpdateConnectionState_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _ConnectionService_UpdateJob_Handler,
		},
		{
			MethodName: "UpdateLines",
			Handler:    _ConnectionService_UpdateLines_Handler,
		},
		{
			MethodName: "GetAddress",
			Handler:    _ConnectionService_GetAddress_Handler,
		},
		{
			MethodName: "GetDeviceBySerialNumber",
			Handler:    _ConnectionService_GetDeviceBySerialNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection-service.proto",
}
